[tool.pytest.ini_options]
addopts = "--pdbcls=IPython.terminal.debugger:Pdb"
filterwarnings = [
    "error",
    "ignore::UserWarning",
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore:function ham\(\) is deprecated:DeprecationWarning',
]