python_library(
    name = 'strategy',
    sources = [
        'strategy/**/*.py',
    ],
    dependencies = [
    ],
)

python_library(
    name = 'grid',
    sources = [
        'grid/**/*.py',
    ],
    dependencies = [
    ],
)